### ISSUE TITLE
Unable to create bucket — "Could not reach quorum of 1" despite single-node setup (Unraid compose)

### ISSUE THREAD

**Issue by ereynier** [khairul169/garage-webui#13]
# Unable to create bucket — "Could not reach quorum of 1" despite single-node setup

## Description

Hi,

I’m running Garage v1.0.1 on Unraid with the following setup:

- Single node deployment using Docker Compose (config below).
- Storage and metadata directories are correctly mounted and have full permissions.
- `rpc_public_addr` is set to `"garage:3901"` to allow cross-container communication.
- Replication factor set to 1 (single node).
- When accessing the WebUI, it shows:
  - 1 Node
  - 0 Storage Nodes
  - 256 Active Storage Nodes (seems off)
- Attempting to create a new bucket results in the error:

```sh
error 503 Service Unavailable, Internal error: Could not reach quorum of 1 (sets=Some(1)). 0 of 0 request succeeded, others returned errors: []
```

---

## garage.toml

```toml
metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"
metadata_auto_snapshot_interval = "6h"

replication_factor = 1
compression_level = 2

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "garage:3901"
rpc_secret = "..."

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "..."
metrics_token = "..."
```

---

## docker-compose-yml

```yaml
services:
  garage:
    image: dxflrs/garage:v1.0.1
    container_name: garage
    volumes:
      - /mnt/user/appdata/garage/garage.toml:/etc/garage.toml
      - /mnt/user/appdata/garage/meta:/var/lib/garage/meta
      - /mnt/user/appdata/garage/data:/var/lib/garage/data
    restart: unless-stopped
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/garage/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
```
---
### Additional info:

- Permissions on /mnt/user/appdata/garage/meta and /mnt/user/appdata/garage/data are 777 and verified writable from outside the container.
- Containers run on the default Docker network and can resolve each other by service name.
- No shell available inside the garage container to debug further.
- Logs show no clear errors at startup, only the quorum error on bucket creation.

---

### Question:

- Why does the node not register as a storage node despite proper config and single node setup?
- Is there a missing flag or config needed for a single node cluster?
- Any advice or steps to troubleshoot this further?

Thanks!
