### ISSUE TITLE
Container can't connect to Garage

### ISSUE THREAD

**Issue by OliverGeneser** [khairul169/garage-webui#3]
Hey! I'm trying to get the webui to run and I'm using the provided garage.toml and docker-compose.yml.

I keep getting this error that it can't connect to the Garage admin API.

```
[garage] | 2024-11-18T09:01:31.578246Z  INFO garage_api::generic_server: S3 API server listening on http://[::]:3900
[garage] | 2024-11-18T09:01:31.578249Z  INFO garage_web::web_server: Web server listening on http://[::]:3902
[garage] | 2024-11-18T09:01:31.578255Z  INFO garage_net::netapp: Listening on [::]:3901
[garage] | 2024-11-18T09:01:31.578294Z  INFO garage_rpc::system: Doing a bootstrap/discovery step (not_configured: true, no_peers: false, bad_peers: true)
[garage] | 2024-11-18T09:01:31.578332Z  INFO garage_api::generic_server: Admin API server listening on http://[::]:3903
[webui]  | 2024/11/18 09:01:31 Starting server on http://0.0.0.0:3909
[webui]  | 2024/11/18 09:01:35 http: proxy error: dial tcp [::1]:3903: connect: connection refused
[webui]  | 2024/11/18 09:01:35 http: proxy error: dial tcp [::1]:3903: connect: connection refused
```
Any solutions?

**Comment by khairul169** [comment]
Hi there!
Could you send me your `docker-compose.yml` file and `rpc_public_addr` value from your garage.toml config? Thanks! :)

**Comment by OliverGeneser** [comment]
It's the exact same as the README, but with generated values in rpc_secret, admin_token and metrics_token :)

**Comment by khairul169** [comment]
I just tried using the exact same configuration as in the README, and yeah, it’s broken. I can’t connect to the Garage Admin API because the WebUI is on a different network than the Garage service.

Could you try adding these lines to your WebUI service in the docker-compose.yml file?
```diff
  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
+   extra_hosts:
+     - "host.docker.internal:host-gateway"
+   environment:
+     API_BASE_URL: "http://host.docker.internal:3903"
```

Please let me know if it still not working, thanks :)

**Comment by OliverGeneser** [comment]
Hmm now it can't start 
```
[webui]  | Error: unable to start container 23db01deb3da8f9d2e81b9e8d4af880b0b7891267b0ec68807076a98dc4891a0: failed to create new hosts file: unable to replace "host-gateway" of host entry "host.docker.internal:host-gateway": host containers internal IP address is empty
```

**Comment by khairul169** [comment]
okay, please try this one:
docker-compose.yml
```yaml
services:
  garage:
    image: dxflrs/garage:v1.0.1
    container_name: garage
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./meta:/var/lib/garage/meta
      - ./data:/var/lib/garage/data
    restart: unless-stopped
    ports:
       - 3900:3900
       - 3901:3901
       - 3902:3903
       - 3903:3903

  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"
````
